name: Deploy ShopMate To AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  APP_NAME: shopmate
  APP_ENV: prod
  GITHUB_BRANCH: main
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::055679187407:role/AWS_GITHUB_ACTIONS_ROLE
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2 via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:App,Values=shopmate" "Key=tag:Environment,Values=prod" \
            --comment "Deploy ShopMate from GitHub Actions" \
            --parameters '{
              "commands": [
                "set -e",

                "echo === Preparing server ===",

                "command -v git >/dev/null 2>&1 || sudo yum install -y git unzip",

                "git --version",

                "rm -rf /opt/shopmate",
                "mkdir -p /opt/shopmate",

                "echo Cloning repository...",

                "git clone https://x-access-token:'"${GH_PAT}"'@github.com/Govindu-Thejana/ShopPal.git /opt/shopmate",

                "cd /opt/shopmate",

                "chmod +x deploy/aws/deploy.sh deploy/aws/write-env.sh",

                "./deploy/aws/deploy.sh"
              ]
            }' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          sleep 20

          aws ssm list-command-invocations \
            --command-id "$COMMAND_ID" \
            --details
